export {Header} from "./Header"
export {Footer} from "./Footer"
export {Hero} from "./Hero"
export {Nature} from "./Nature"
export {Gallery} from "./Gallery"
export {Family} from "./Family"
export {Services} from "./Services"
export {Trip} from "./Trip"